V3 store other reason field
vtex-apps/return-app pull request #93
Opened 2022-05-02 15:06 UTC by zekivtex

What is the purpose of this PR?
Render Textarea to allow user to describe another reason for the return request.

How to test it?
Select otherReason option on [this workspace](https://reason--powerplanet.myvtex.com/account?__bindingAddress=www.we-demostore.com/es#/my-returns/add/1224161013423-01)

2022-05-02 16:01 UTC, filafb requested changes

2022-05-02 16:01 UTC, filafb commented on react/store/createReturnRequest/components/ItemsDetails.tsx
> +          otherReason,
I would only add this property if the reason is otherReason. This way, we keep the pattern as: If the reason is different than `otherReason`, there is no `otherReason` property on the object. The way we designed here, some can have it as an empty string, other will not have it.

```suggestion
          ...(reason === 'otherReason' ? { otherReason } : null),
```

2022-05-02 16:18 UTC, zekivtex commented on react/store/createReturnRequest/components/RenderReasonDropdown.tsx
> +      {isOtherReason ? (
Nice! I agree

2022-05-03 11:05 UTC, filafb approved these changes

2022-05-03 11:06 UTC, merged